project_id = "oglduptdtrlxqglapjaj"

[functions.institutional-api]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false

[functions.market-analysis]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false
