project_id = "oglduptdtrlxqglapjaj"

[functions.verify-captcha]
verify_jwt = false

[functions.market-analysis]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.pro-ai-suggestions]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false
